### ISSUE TITLE
Clicking "home" icon logs out. 

### ISSUE THREAD

**Issue by ayman** [CCI-MIT/minglr#1]
If I login with my email (not via google or facebook), then click the logo in the top left:
<img width="201" alt="image" src="https://user-images.githubusercontent.com/1846/89218382-c96c3c80-d582-11ea-8a15-c243e1db356e.png">
It takes me back to the login page: https://APP.herokuapp.com/ with this error
<img width="410" alt="image" src="https://user-images.githubusercontent.com/1846/89218460-eacd2880-d582-11ea-8476-7ab9989a86a6.png">
but i'm not logged out as going to https://APP.herokuapp.com/home takes me back to the event without login needed.

**Comment by jyoonsong** [comment]
Thanks so much! It is now fixed in 21e24d1638e53d49906fb5fa1dcebd46e1400183
